### PR TITLE
Added notifications

### PR DESCRIPTION
**Pull request by alexkahn139**
Added notifications, this should work for different OS'es. I used node-notifier, wich should be installed using `npm install --save node-notifier`

### CODE REVIEW

**Comment by alexkahn139** [comment]
This should also fix, some problems that happens if the user sends messages using another app or device

**Comment by alexkahn139** [comment]
I Will try to fix this soon and reupload it

**Comment by evanyeung** [comment]
Merged. Thanks for contributing!

**Comment by alexkahn139** [comment]
You should maybe still change the .md file. Because you need `node-notifier` or does the `npm install` do this?

**Comment by evanyeung** [comment]
Since the `package.json` file is updated with `node-notifier` as a dependency, `npm install` will install it.

**Pull request merged**
