### PR TITLE
Add IM support

### PR DESCRIPTION
**Pull request by passabilities**
• Users list for sending direct messages.
• Remove `node_modules` folder from repo.

### CODE REVIEW

**Comment by passa763** [comment]
Removed the `node_modules` folder in reference to PR #4

**Comment by passa763** [comment]
Maybe I'm just too tired, but I could use some help with updating the ui for `onFocus` and `onBlur` for changing the box border colors

**Comment by passabilities** [comment]
@evanyeung what are your thoughts? I'm working on a better chat log UI to make it more readable as well

**Comment by vinhnglx** [comment]
:+1: waiting this pr merged :)

**Comment by JeremyHargis** [comment]
This would be great!

**Comment by halvves** [comment]
@evanyeung, this is a really cool project, and I love all of the work you have done, but should we treat @passabilities' fork (his seems to have the most active improvements) as the new canonical fork, as this repo doesn't seem to be actively maintained?

I mean no offense. I just don't want to see this project die.

**Comment by passabilities** [comment]
Yea its been awhile since I touched this. I don't have as much free time atm to keep making updates. I can add anyone as a collaborator to my repo for now until this PR gets approved if you want to continue working off this.

**Comment by evanyeung** [comment]
@passabilities Thanks for your work on this! Sorry it took a while for me to get around to reviewing the PR. I made a couple edits to the UI and merged this to master.

**Pull request merged**
